CREATE TABLE [dbo].[den_customer] (
    [CustomerId]         INT           NOT NULL,
    [FirstName]          NVARCHAR (40) NOT NULL,
    [LastName]           NVARCHAR (20) NOT NULL,
    [Company]            NVARCHAR (80) NULL,
    [Address]            NVARCHAR (70) NULL,
    [City]               NVARCHAR (40) NULL,
    [State]              NVARCHAR (40) NULL,
    [Country]            NVARCHAR (40) NULL,
    [PostalCode]         NVARCHAR (10) NULL,
    [Phone]              NVARCHAR (24) NULL,
    [Fax]                NVARCHAR (24) NULL,
    [Email]              NVARCHAR (60) NOT NULL,
    [SupportRepId]       INT           NULL,
    [Support_FirstName]  NVARCHAR (20) NOT NULL,
    [Support_LastName]   NVARCHAR (20) NOT NULL,
    [Support_Tittle]     NVARCHAR (30) NULL,
    [Support_ReportsTo]  NVARCHAR (41) NOT NULL,
    [Support_BirthDate]  DATETIME      NULL,
    [Support_HireDate]   DATETIME      NULL,
    [Suppport_Adress]    NVARCHAR (70) NULL,
    [Support_City]       NVARCHAR (40) NULL,
    [Support_State]      NVARCHAR (40) NULL,
    [Support_Country]    NVARCHAR (40) NULL,
    [Support_PostalCode] NVARCHAR (10) NULL,
    [Support_Phone]      NVARCHAR (24) NULL,
    [Support_Fax]        NVARCHAR (24) NULL,
    [Support_Email]      NVARCHAR (60) NULL
);

